### ISSUE TITLE
Any write-up of the project available?

### ISSUE THREAD

**Issue by jonnor** [veysiadn/postural_sway_analysis#1]
Hi.  It seems that you are using emlearn in this project.
Do you have any write-up about the project, be a it a blogpost, video, techreport, paper et.c?
If so, we would be happy to include a link to it in the "Using emlearn" section of our documentation.

Best regards, Jon

**Comment by veysiadn** [comment]
Hello, actually we used emlearn for deploying several sklearn models and wrote a conference paper which will be presented at the end of July. In the meantime, you can access the paper here: https://github.com/veysiadn/veysiadn.github.io/raw/master/assets/pdf/1570901064%20final.pdf 
Maybe in the future, I'll write detailed instructions about it, but for now, we used this library only for deployment and still exploring other options to make a comparison.
Best regards,
Veysi

**Comment by jonnor** [comment]
Hi,
thank you for the response. That conference paper looks great, I will have
a read though it.
And then after it has been presented in July I can link to it in the
emlearn project?

**Comment by veysiadn** [comment]
Sure, you can provide a link to it in the emlearn project repo. Thank you for providing such a nice open-source repo and making deployment so convenient.

**Comment by jonnor** [comment]
Great, I will do that.
I am glad you found the project useful and that it worked as intended :)

**Comment by jonnor** [comment]
I wrote about it in the emlearn README now.
